"""D3 tight-binding and Landau-fan utilities packaged with this workspace."""

from .d3_physical_reservoir import (
    ParticleBreakdownMetrics,
    PhysicalReservoirParams,
    ReservoirWindowMetrics,
    bands as d3_physical_reservoir_bands,
    construct_single_reservoir_candidate as d3_construct_single_reservoir_candidate,
    d0_value as d3_physical_reservoir_d0_value,
    hamiltonian as d3_physical_reservoir_hamiltonian,
    particle_breakdown_metrics as d3_particle_breakdown_metrics,
    reservoir_window_metrics as d3_reservoir_window_metrics,
)
from .d3_two_band import (
    D3TwoBandParameters,
    background_candidate_parameters as d3_background_candidate_parameters,
    baseline_candidate_parameters as d3_baseline_candidate_parameters,
    c1_harmonic,
    c2_harmonic,
    candidate_report as d3_candidate_report,
    d0_term as d3_d0_term,
    eigvals as d3_eigvals,
    find_line_dirac_roots as d3_find_line_dirac_roots,
    g_harmonic,
    hamiltonian as d3_hamiltonian,
    m_term as d3_m_term,
    slope_reversal_candidate_parameters as d3_slope_reversal_candidate_parameters,
    starting_candidate_parameters as d3_starting_candidate_parameters,
    strong_bending_candidate_parameters as d3_strong_bending_candidate_parameters,
    tb_model as d3_tb_model,
)
from .dos import (
    FanResult,
    apply_beta_hybridization_gap,
    beta_reservoir_dos,
    gaussian_dos,
    histogram_gaussian_dos,
    magnetic_breakdown_replicated_spectrum,
    regrid_dos_to_density,
    saddle_window_gaussian_dos,
    track_low_dos_branches,
    track_low_dos_branches_dp,
)
from .peierls_hofstadter import (
    HofstadterSpectrum,
    TBModel,
    magnetic_field_tesla_from_q,
    magnetic_hamiltonian,
    magnetic_kmesh,
    peierls_phase,
    rational_flux_grid_for_b_field,
    spectrum_at_flux,
)
from .tb_hofstadter_lfd_workflow import (
    PureHofstadterDOSResult,
    compute_pure_hofstadter_dos,
    selected_d3_parameters,
)

__all__ = [
    "D3TwoBandParameters",
    "FanResult",
    "HofstadterSpectrum",
    "ParticleBreakdownMetrics",
    "PhysicalReservoirParams",
    "PureHofstadterDOSResult",
    "ReservoirWindowMetrics",
    "TBModel",
    "apply_beta_hybridization_gap",
    "beta_reservoir_dos",
    "c1_harmonic",
    "c2_harmonic",
    "compute_pure_hofstadter_dos",
    "d3_background_candidate_parameters",
    "d3_baseline_candidate_parameters",
    "d3_candidate_report",
    "d3_construct_single_reservoir_candidate",
    "d3_d0_term",
    "d3_eigvals",
    "d3_find_line_dirac_roots",
    "d3_hamiltonian",
    "d3_m_term",
    "d3_physical_reservoir_bands",
    "d3_physical_reservoir_d0_value",
    "d3_physical_reservoir_hamiltonian",
    "d3_particle_breakdown_metrics",
    "d3_reservoir_window_metrics",
    "d3_slope_reversal_candidate_parameters",
    "d3_starting_candidate_parameters",
    "d3_strong_bending_candidate_parameters",
    "d3_tb_model",
    "g_harmonic",
    "gaussian_dos",
    "histogram_gaussian_dos",
    "magnetic_breakdown_replicated_spectrum",
    "magnetic_field_tesla_from_q",
    "magnetic_hamiltonian",
    "magnetic_kmesh",
    "peierls_phase",
    "rational_flux_grid_for_b_field",
    "regrid_dos_to_density",
    "saddle_window_gaussian_dos",
    "selected_d3_parameters",
    "spectrum_at_flux",
    "track_low_dos_branches",
    "track_low_dos_branches_dp",
]
